owner: shipcommit
repo: upptime

sites:
  - name: Visulry Health Check
    url: https://visulry.com/health
  - name: Visulry Articles Data
    url: https://visulry.com/articles/__data.json

status-website:
  name: Upptime
  baseUrl: /upptime
